# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/eleves/Desktop/uart_ascon_light_el/.Xil/Vivado-1712-GCP-E105-26/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv {
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/ascon_pack.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/Pc.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/Permutation.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/Pl.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/Ps.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/Sbox.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/uart_pkg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/ad_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/ascon.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/ascon_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/baud_generator.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/cipher_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/fsmAscon/compteur.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/compteur_double_init.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/fsmAscon/fsm.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/fsm_dcounter.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/fsm_moore.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/fsm_uart.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/key_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/mux_state.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/nonce_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/receive.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/reg_sel.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/register_w_en.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/rx_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/rxbit_dcounter.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/state_register_w_en.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/tag_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/trans_receive.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/transmit.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/tx_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/txbit_dcounter.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/uart_core.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/wave_reg.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/xor_begin_perm.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/Sources_ascon-20250324/xor_end_perm.sv
      C:/Users/eleves/Desktop/uart_ascon_light_el/uart_ascon_light_el.srcs/sources_1/imports/RTL2/inter_spartan.sv
    }
      rt::read_verilog {
      C:/Users/eleves/Desktop/uart_ascon_light_el/.Xil/Vivado-1712-GCP-E105-26/realtime/clk_wiz_1_stub.v
      C:/Users/eleves/Desktop/uart_ascon_light_el/.Xil/Vivado-1712-GCP-E105-26/realtime/ila_0_stub.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top inter_spartan
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/eleves/Desktop/uart_ascon_light_el/.Xil/Vivado-1712-GCP-E105-26/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
