############################
# On-board leds             #
############################
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {Baud_o[0]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {Baud_o[1]}]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {Baud_o[2]}]
#set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports {Baud_o[3]}]

####
# ----------------------------------------------------------------------------
# User PUSH Switches - Bank 35
# ----------------------------------------------------------------------------
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {Baud_i[0]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports {Baud_i[1]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {Baud_i[2]}]
#resetb_i
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports reset_i]

## Clock signal 125 MHz

set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports clock_i]
#create_clock -add -name sys_clk_pin -period 8.00 -waveform {0 4} [get_ports { clock_i }];

#UART PMODA pin jap1-> RTS jan1-> Tx_o jap2-> Rx_o
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports RTS_o]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports Tx_o]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports Rx_i]

set_property MARK_DEBUG true [get_nets {wave_s[7]}]
set_property MARK_DEBUG true [get_nets {wave_s[0]}]
set_property MARK_DEBUG true [get_nets {wave_s[2]}]
set_property MARK_DEBUG true [get_nets {wave_s[40]}]
set_property MARK_DEBUG true [get_nets {wave_s[46]}]
set_property MARK_DEBUG true [get_nets {wave_s[44]}]
set_property MARK_DEBUG true [get_nets {wave_s[51]}]
set_property MARK_DEBUG true [get_nets {wave_s[13]}]
set_property MARK_DEBUG true [get_nets {wave_s[3]}]
set_property MARK_DEBUG true [get_nets {wave_s[29]}]
set_property MARK_DEBUG true [get_nets {wave_s[33]}]
set_property MARK_DEBUG true [get_nets {wave_s[6]}]
set_property MARK_DEBUG true [get_nets {wave_s[17]}]
set_property MARK_DEBUG true [get_nets {wave_s[56]}]
set_property MARK_DEBUG true [get_nets {wave_s[57]}]
set_property MARK_DEBUG true [get_nets {wave_s[61]}]
set_property MARK_DEBUG true [get_nets {wave_s[32]}]
set_property MARK_DEBUG true [get_nets {wave_s[27]}]
set_property MARK_DEBUG true [get_nets {wave_s[12]}]
set_property MARK_DEBUG true [get_nets {wave_s[21]}]
set_property MARK_DEBUG true [get_nets {wave_s[30]}]
set_property MARK_DEBUG true [get_nets {wave_s[38]}]
set_property MARK_DEBUG true [get_nets {wave_s[31]}]
set_property MARK_DEBUG true [get_nets {wave_s[50]}]
set_property MARK_DEBUG true [get_nets {wave_s[59]}]
set_property MARK_DEBUG true [get_nets {wave_s[63]}]
set_property MARK_DEBUG true [get_nets {wave_s[5]}]
set_property MARK_DEBUG true [get_nets {wave_s[10]}]
set_property MARK_DEBUG true [get_nets {wave_s[47]}]
set_property MARK_DEBUG true [get_nets {wave_s[19]}]
set_property MARK_DEBUG true [get_nets {wave_s[48]}]
set_property MARK_DEBUG true [get_nets {wave_s[23]}]
set_property MARK_DEBUG true [get_nets {wave_s[43]}]
set_property MARK_DEBUG true [get_nets {wave_s[8]}]
set_property MARK_DEBUG true [get_nets {wave_s[9]}]
set_property MARK_DEBUG true [get_nets {wave_s[11]}]
set_property MARK_DEBUG true [get_nets {wave_s[35]}]
set_property MARK_DEBUG true [get_nets {wave_s[45]}]
set_property MARK_DEBUG true [get_nets {wave_s[58]}]
set_property MARK_DEBUG true [get_nets {wave_s[60]}]
set_property MARK_DEBUG true [get_nets {wave_s[1]}]
set_property MARK_DEBUG true [get_nets {wave_s[24]}]
set_property MARK_DEBUG true [get_nets {wave_s[42]}]
set_property MARK_DEBUG true [get_nets {wave_s[52]}]
set_property MARK_DEBUG true [get_nets {wave_s[37]}]
set_property MARK_DEBUG true [get_nets {wave_s[4]}]
set_property MARK_DEBUG true [get_nets {wave_s[16]}]
set_property MARK_DEBUG true [get_nets {wave_s[55]}]
set_property MARK_DEBUG true [get_nets {wave_s[26]}]
set_property MARK_DEBUG true [get_nets {wave_s[25]}]
set_property MARK_DEBUG true [get_nets {wave_s[15]}]
set_property MARK_DEBUG true [get_nets {wave_s[14]}]
set_property MARK_DEBUG true [get_nets {wave_s[22]}]
set_property MARK_DEBUG true [get_nets {wave_s[28]}]
set_property MARK_DEBUG true [get_nets {wave_s[41]}]
set_property MARK_DEBUG true [get_nets {wave_s[36]}]
set_property MARK_DEBUG true [get_nets {wave_s[54]}]
set_property MARK_DEBUG true [get_nets {wave_s[62]}]
set_property MARK_DEBUG true [get_nets {wave_s[18]}]
set_property MARK_DEBUG true [get_nets {wave_s[20]}]
set_property MARK_DEBUG true [get_nets {wave_s[34]}]
set_property MARK_DEBUG true [get_nets {wave_s[39]}]
set_property MARK_DEBUG true [get_nets {wave_s[49]}]
set_property MARK_DEBUG true [get_nets {wave_s[53]}]
set_property MARK_DEBUG true [get_nets RTS_o_OBUF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_conv/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 64 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {wave_s[0]} {wave_s[1]} {wave_s[2]} {wave_s[3]} {wave_s[4]} {wave_s[5]} {wave_s[6]} {wave_s[7]} {wave_s[8]} {wave_s[9]} {wave_s[10]} {wave_s[11]} {wave_s[12]} {wave_s[13]} {wave_s[14]} {wave_s[15]} {wave_s[16]} {wave_s[17]} {wave_s[18]} {wave_s[19]} {wave_s[20]} {wave_s[21]} {wave_s[22]} {wave_s[23]} {wave_s[24]} {wave_s[25]} {wave_s[26]} {wave_s[27]} {wave_s[28]} {wave_s[29]} {wave_s[30]} {wave_s[31]} {wave_s[32]} {wave_s[33]} {wave_s[34]} {wave_s[35]} {wave_s[36]} {wave_s[37]} {wave_s[38]} {wave_s[39]} {wave_s[40]} {wave_s[41]} {wave_s[42]} {wave_s[43]} {wave_s[44]} {wave_s[45]} {wave_s[46]} {wave_s[47]} {wave_s[48]} {wave_s[49]} {wave_s[50]} {wave_s[51]} {wave_s[52]} {wave_s[53]} {wave_s[54]} {wave_s[55]} {wave_s[56]} {wave_s[57]} {wave_s[58]} {wave_s[59]} {wave_s[60]} {wave_s[61]} {wave_s[62]} {wave_s[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list RTS_o_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clock_50MHZ_s]
